 # Usar la imagen oficial de Node.js como imagen base
 FROM node:16
 # Establecer el directorio de trabajo en el contenedor
 WORKDIR /usr/src/app
 # Copiar package.json y package-lock.json (si está disponible)
 COPY package*.json ./
 # Instalar dependencias del proyecto
 RUN npm install
 # Copiar los archivos del proyecto al directorio de trabajo del contenedor
 COPY . .
 # Exponer el puerto en el que la aplicación se ejecutará
 EXPOSE 3000
 # Comando para ejecutar la aplicación
 CMD ["node", "index.js"]